site_name: Docs
site_url: https://sujiba.github.io

theme:
  name: material
  icon:
    logo: material/library
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  language: de
  features:
    - navigation.tracking
    - navigation.tabs
  # Prevents typefaces from being loaded from google fonts
  font: false

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sujiba
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/sujiba

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables

copyright: Copyright &copy; 2022 - 2023 sujiba

# Page tree
nav:
  - Home: index.md
  - Wiki:
      - wiki/index.md
      - Hetzner x Restic: wiki/hetzner_x_restic.md
      - Home Assistant: wiki/homeassistant.md
  - Home-Ops:
      - home-ops/index.md
